/*
 * SPDX-License-Identifier: MPL-2.0
 */

#ifndef RUNTIME_API_SLOTS_H_
#define RUNTIME_API_SLOTS_H_

#define RTBUS_API_MAGIC      0x52544150U
#define RTBUS_API_VERSION    12U
#define RTBUS_ENOSYS         38
#define RTBUS_EINVAL         22
#define RTBUS_EMSGSIZE       90
#define RTBUS_EINPROGRESS    115
#define RTBUS_WAIT_FOREVER   0xFFFFFFFFU

#define RTBUS_API_SLOT_MAGIC          0
#define RTBUS_API_SLOT_VERSION        1
#define RTBUS_API_SLOT_SLOT_COUNT     2
#define RTBUS_API_SLOT_RTBUS_POST     3
#define RTBUS_API_SLOT_DELAY          4
#define RTBUS_API_SLOT_RTT_PRINTF     5
#define RTBUS_API_SLOT_RTT_VPRINTF    6
#define RTBUS_API_SLOT_RESULT_WAIT    7
#define RTBUS_API_SLOT_SERIAL_WRITE   8
#define RTBUS_API_SLOT_GPIO_CONFIGURE 9
#define RTBUS_API_SLOT_GPIO_WRITE     10
#define RTBUS_API_SLOT_GPIO_READ      11
#define RTBUS_API_SLOT_ON_EVENT       12
#define RTBUS_API_SLOT_SERIAL_VPRINTF 13
#define RTBUS_API_SLOT_SERIAL_READ    14
#define RTBUS_API_SLOT_MILLIS         15
#define RTBUS_API_SLOT_COUNT          16

#define RTBUS_API_SLOT_OFFSET(_slot) ((_slot) * 4)

#endif /* RUNTIME_API_SLOTS_H_ */
